apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    se7entyse7en.prometheus/scrape: "true"
    se7entyse7en.prometheus/path: "/metrics"
    se7entyse7en.prometheus/port: "9191"
spec:
  selector:
    app: app
  ports:
  - port: 9191
